# Generated by Django 4.2.7 on 2023-11-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perevaladded',
            name='beautyTitle',
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='beauty_title',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
