# Generated by Django 4.2.7 on 2023-11-27 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0002_remove_perevaladded_beautytitle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='mail',
            new_name='email',
        ),
    ]
