# Generated by Django 4.2.7 on 2023-11-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0003_rename_mail_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='connect',
            field=models.TextField(max_length=128),
        ),
    ]
